In [11]:
import geopandas as gpd
import  os 
import pandas as pd 
usuario = os.getlogin()

In [2]:

yucatan = gpd.read_file(fr"C:\Users\{usuario}\Downloads\Anexo_1_yuc_validado.gpkg")

In [12]:
base = gpd.read_file(fr"C:\Users\{usuario}\IMSS-BIENESTAR\División de Procesamiento de información - Comando Florence Nightingale\Proyectos\115_Isocronas_interserccion\Data raw\1ER_NIVEL_IMB_IMO.gpkg")

In [4]:
base = base[base["nivel_atencion"]=="PRIMER NIVEL"]

In [5]:
base

,clues,clave_de_la_institucion,clave_de_la_entidad,entidad,clave_del_municipio,municipio,clave_de_la_localidad,localidad,nombre_de_tipologia,nombre_de_subtipologia,nombre_unidad,nombre_comercial,estatus_de_operacion,nivel_atencion,geometry
0,BCIMS000513,IMO,02,BAJA CALIFORNIA,006,SAN QUINTIN,0040,CAMALU,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,CAMALÚ,CAMALÚ,EN OPERACION,PRIMER NIVEL,POINT (-116.06507 30.84503)
1,BCIMS000525,IMO,02,BAJA CALIFORNIA,006,SAN QUINTIN,0585,LAZARO CARDENAS,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,LÁZARO CÁRDENAS (SAN QUINTIN),LÁZARO CÁRDENAS (SAN QUINTIN),EN OPERACION,PRIMER NIVEL,POINT (-115.92796 30.52928)
2,BCIMS000530,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0186,EJIDO PUNTA COLNETT (PUNTA COLONET),UNIDAD MÉDICA RURAL,NO ESPECIFICADO,EJIDO MÉXICO (EJIDO PUNTA COLONET),EJIDO MÉXICO (EJIDO PUNTA COLONET),EN OPERACION,PRIMER NIVEL,POINT (-116.20818 31.07187)
3,BCIMS000542,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0242,SANTO TOMAS,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,SANTO TOMÁS (ENSENADA),SANTO TOMÁS (ENSENADA),EN OPERACION,PRIMER NIVEL,POINT (-116.40101 31.54794)
4,BCIMS000554,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0617,EL PORVENIR (GUADALUPE),UNIDAD MÉDICA RURAL,NO ESPECIFICADO,EL PORVENIR (GUADALUPE),EL PORVENIR (GUADALUPE),EN OPERACION,PRIMER NIVEL,POINT (-116.6241 32.07778)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11876,ZSIMB002505,IMB,32,ZACATECAS,039,RIO GRANDE,0001,RIO GRANDE,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA RÍO GRANDE,CESSA RÍO GRANDE,EN OPERACION,PRIMER NIVEL,POINT (-103.01225 23.82886)
11877,ZSIMB002522,IMB,32,ZACATECAS,010,FRESNILLO,0001,FRESNILLO,URBANO DE 06 NÚCLEOS BÁSICOS,NO ESPECIFICADO,CENTRO DE SALUD FRESNILLO 2,CENTRO DE SALUD FRESNILLO 2,EN OPERACION,PRIMER NIVEL,POINT (-102.86467 23.18379)
11878,ZSIMB002534,IMB,32,ZACATECAS,038,PINOS,0001,PINOS,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA PINOS,CESSA PINOS,EN OPERACION,PRIMER NIVEL,POINT (-101.58206 22.27766)
11879,ZSIMB002650,IMB,32,ZACATECAS,020,JEREZ,0001,JEREZ DE GARCIA SALINAS,URBANO DE 07 NÚCLEOS BÁSICOS,NO ESPECIFICADO,CENTRO DE SALUD JEREZ,CENTRO DE SALUD JEREZ,EN OPERACION,PRIMER NIVEL,POINT (-102.98112 22.66127)
11880,OCIMB009672,IMB,20,OAXACA,299,OCOTLAN DE MORELOS,0001,OCOTLAN DE MORELOS,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA DE OCOTLAN DE MORELOS,CESSA DE OCOTLAN DE MORELOS,EN OPERACION,PRIMER NIVEL,POINT (-96.66797 16.79016)

In [13]:
# tipologias = [
#     'CENTROS DE SALUD CON SERVICIOS AMPLIADOS',
#     'UNIDAD MÓVIL',
#     'URBANO DE 01 NÚCLEOS BÁSICOS',
#     'URBANO DE 05 NÚCLEOS BÁSICOS',
#     'RURAL DE 01 NÚCLEO BÁSICO',
#     'URBANO DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 11 NÚCLEOS BÁSICOS',
#     'URBANO DE 12 NÚCLEOS BÁSICOS Y MÁS',
#     'RURAL DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 06 NÚCLEOS BÁSICOS',
#     'URBANO DE 03 NÚCLEOS BÁSICOS',
#     'URBANO DE 07 NÚCLEOS BÁSICOS',
#     'URBANO DE 08 NÚCLEOS BÁSICOS',
#     'URBANO DE 04 NÚCLEOS BÁSICOS'
# ]

# base = base[base['NOMBRE DE TIPOLOGIA'].isin(tipologias)]

In [6]:
conteo_imo = base["clave_de_la_institucion"].unique()
conteo_imo

array(['IMO', 'IMB'], dtype=object)

In [15]:
base

,clues,clave_de_la_institucion,clave_de_la_entidad,entidad,clave_del_municipio,municipio,clave_de_la_localidad,localidad,nombre_de_tipologia,nombre_de_subtipologia,nombre_unidad,nombre_comercial,estatus_de_operacion,nivel_atencion,geometry
0,BCIMS000513,IMO,02,BAJA CALIFORNIA,006,SAN QUINTIN,0040,CAMALU,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,CAMALÚ,CAMALÚ,EN OPERACION,PRIMER NIVEL,POINT (-116.06507 30.84503)
1,BCIMS000525,IMO,02,BAJA CALIFORNIA,006,SAN QUINTIN,0585,LAZARO CARDENAS,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,LÁZARO CÁRDENAS (SAN QUINTIN),LÁZARO CÁRDENAS (SAN QUINTIN),EN OPERACION,PRIMER NIVEL,POINT (-115.92796 30.52928)
2,BCIMS000530,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0186,EJIDO PUNTA COLNETT (PUNTA COLONET),UNIDAD MÉDICA RURAL,NO ESPECIFICADO,EJIDO MÉXICO (EJIDO PUNTA COLONET),EJIDO MÉXICO (EJIDO PUNTA COLONET),EN OPERACION,PRIMER NIVEL,POINT (-116.20818 31.07187)
3,BCIMS000542,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0242,SANTO TOMAS,UNIDAD MÉDICA RURAL,NO ESPECIFICADO,SANTO TOMÁS (ENSENADA),SANTO TOMÁS (ENSENADA),EN OPERACION,PRIMER NIVEL,POINT (-116.40101 31.54794)
4,BCIMS000554,IMO,02,BAJA CALIFORNIA,001,ENSENADA,0617,EL PORVENIR (GUADALUPE),UNIDAD MÉDICA RURAL,NO ESPECIFICADO,EL PORVENIR (GUADALUPE),EL PORVENIR (GUADALUPE),EN OPERACION,PRIMER NIVEL,POINT (-116.6241 32.07778)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11876,ZSIMB002505,IMB,32,ZACATECAS,039,RIO GRANDE,0001,RIO GRANDE,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA RÍO GRANDE,CESSA RÍO GRANDE,EN OPERACION,PRIMER NIVEL,POINT (-103.01225 23.82886)
11877,ZSIMB002522,IMB,32,ZACATECAS,010,FRESNILLO,0001,FRESNILLO,URBANO DE 06 NÚCLEOS BÁSICOS,NO ESPECIFICADO,CENTRO DE SALUD FRESNILLO 2,CENTRO DE SALUD FRESNILLO 2,EN OPERACION,PRIMER NIVEL,POINT (-102.86467 23.18379)
11878,ZSIMB002534,IMB,32,ZACATECAS,038,PINOS,0001,PINOS,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA PINOS,CESSA PINOS,EN OPERACION,PRIMER NIVEL,POINT (-101.58206 22.27766)
11879,ZSIMB002650,IMB,32,ZACATECAS,020,JEREZ,0001,JEREZ DE GARCIA SALINAS,URBANO DE 07 NÚCLEOS BÁSICOS,NO ESPECIFICADO,CENTRO DE SALUD JEREZ,CENTRO DE SALUD JEREZ,EN OPERACION,PRIMER NIVEL,POINT (-102.98112 22.66127)
11880,OCIMB009672,IMB,20,OAXACA,299,OCOTLAN DE MORELOS,0001,OCOTLAN DE MORELOS,CENTROS DE SALUD CON SERVICIOS AMPLIADOS,NO ESPECIFICADO,CESSA DE OCOTLAN DE MORELOS,CESSA DE OCOTLAN DE MORELOS,EN OPERACION,PRIMER NIVEL,POINT (-96.66797 16.79016)

In [16]:
from pathlib import Path

columnas_mapa = [
    "clues",
    "clave_de_la_institucion",
    "entidad",
    "municipio",
    "localidad",
    "nombre_unidad",
    "geometry",
]

base_mapa = base.loc[
    base["nivel_atencion"].eq("PRIMER NIVEL")
    & base["clave_de_la_institucion"].isin(["IMO", "IMB"]),
    columnas_mapa,
].copy()

salida_mapa = Path.cwd() / "public" / "mapa_base.geojson"
base_mapa.to_file(salida_mapa, driver="GeoJSON")

print(base_mapa["clave_de_la_institucion"].value_counts().to_dict())
print(f"GeoJSON generado: {salida_mapa} ({len(base_mapa):,} CLUES)")

{'IMB': 8261, 'IMO': 3620}
GeoJSON generado: c:\Users\jose.valdez\Downloads\mapa_imo\mapa_primer_nivel\public\mapa_base.geojson (11,881 CLUES)