In [1]:
import geopandas as gpd
import  os 
import pandas as pd 
usuario = os.getlogin()

In [2]:

# yucatan = gpd.read_file(fr"C:\Users\{usuario}\Downloads\Anexo_1_yuc_validado.gpkg")

In [3]:
mapa_ant = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\base_casas_analizadas2026_09_16.gpkg")

In [4]:
mapa_ant.columns

Index(['entidad', 'municipio', 'localidad', 'nombre', 'id_temp_sus',
       'aceptado', 'motivo_rechazo', 'clues_ancla', 'tiempo_min', 'dist_km',
       'geometry'],
      dtype='object')

In [5]:
base_casas = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\actualizacion_casas_salud_SUN.xlsx")

In [6]:
len(base_casas)

3644

In [7]:
base_casas

,entidad,municipio,localidad,nombre,id_temp_sus,aceptado,motivo_rechazo,clues_ancla,tiempo_min,dist_km
0,BAJA CALIFORNIA,ENSENADA,ENSENADA,CASA DE CUIDADO,BCN-SUS-0001,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCIMB000104,3.9,1.988
1,BAJA CALIFORNIA,ENSENADA,EJIDO FRANCISCO R. SERRANO (VALLE SAN MATÍAS),CASA DE SALUD KILIWAS,BCN-SUS-0002,Aceptada,Aceptada,BCIMB000314,43.9,22.735
2,BAJA CALIFORNIA,ENSENADA,LA HUERTA,CASA DE SALUD LA HUERTA,BCN-SUS-0003,Aceptada,Aceptada,BCIMB000191,35.8,17.404
3,BAJA CALIFORNIA,ENSENADA,SAN ANTONIO NECUA (CAÑADA DE LOS ENCINOS),CASA DE SALUD SAN ANTONIO NECUA,BCN-SUS-0004,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",BCIMB001270,11.8,8.667
4,BAJA CALIFORNIA,ENSENADA,ENSENADA,CASA DE SALUD SEXTO AYUNTAMIENTO,BCN-SUS-0005,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCIMB001516,2.2,0.834
...,...,...,...,...,...,...,...,...,...,...
3639,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ,VERACRUZ,EX CASETA DE POLICIA,VER-SUS-1208,Aceptadas por pertenecer al SUN,Otra casa de salud ofrece una mejor ubicación,VZIMB005562,3.0,1.631
3640,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ,VERACRUZ,EX DIRECCIÓN DE DESARROLLO SOCIAL Y HUMANO,VER-SUS-1213,Aceptadas por pertenecer al SUN,Otra casa de salud ofrece una mejor ubicación,VZIMB005545,5.1,3.351
3641,YUCATAN,ESPITA,ESPITA,"KUNCHE, ESPITA, YUCATÁN",YUC-SUS-0057,No aceptada,No mejora ubicacion respecto a unidades existe...,QRIMB001471,102.2,100.632
3642,YUCATAN,MUXUPIP,MUXUPIP,CASA SALUD MUXUPIP,YUC-SUS-0121,No aceptada,No mejora ubicacion respecto a unidades existe...,CCIMB000020,98.1,114.708
3643,YUCATAN,SUMA,SUMA,CONSULTORIO,YUC-SUS-0157,No aceptada,No mejora ubicacion respecto a unidades existe...,CCIMB000020,109.7,139.923

In [8]:
columnas_join = [
    'entidad', 'municipio', 'localidad', 'nombre', 'id_temp_sus',
    'aceptado', 'motivo_rechazo', 'clues_ancla', 'tiempo_min', 'dist_km',
]
for tabla in (mapa_ant, base_casas):
    tabla['aceptado'] = tabla['aceptado'].astype('string').str.strip()
    tabla.loc[
        tabla['aceptado'].eq('Aceptadas por pertenecer al SUN'),
        'aceptado',
    ] = 'Aceptada'

geometrias_mapa_ant = (
    mapa_ant.loc[:, columnas_join + ['geometry']]
    .drop_duplicates(subset=columnas_join)
)
base_casas = (
    base_casas.drop(columns=['geometry'], errors='ignore')
    .merge(geometrias_mapa_ant, on=columnas_join, how='left', validate='many_to_one')
)
geometrias_por_id = (
    mapa_ant.assign(id_temp_sus=mapa_ant['id_temp_sus'].astype('string').str.strip())
    .drop_duplicates(subset='id_temp_sus')
    .set_index('id_temp_sus')['geometry']
)
ids_casas = base_casas['id_temp_sus'].astype('string').str.strip()
base_casas['geometry'] = base_casas['geometry'].fillna(ids_casas.map(geometrias_por_id))
base_casas = gpd.GeoDataFrame(base_casas, geometry='geometry', crs=mapa_ant.crs)

base_casas_aceptadas = base_casas[base_casas['aceptado'].eq('Aceptada')].copy()
base_casas_no_aceptadas = base_casas[base_casas['aceptado'].eq('No aceptada')].copy()
print(f"Aceptadas: {len(base_casas_aceptadas):,}")
print(f"No aceptadas: {len(base_casas_no_aceptadas):,}")

Aceptadas: 1,999
No aceptadas: 1,645

In [9]:
base_casas.columns

Index(['entidad', 'municipio', 'localidad', 'nombre', 'id_temp_sus',
       'aceptado', 'motivo_rechazo', 'clues_ancla', 'tiempo_min', 'dist_km',
       'geometry'],
      dtype='object')

In [10]:
conteo_base = base_casas['aceptado'].unique()
conteo_base

<StringArray>
['Aceptada', 'No aceptada']
Length: 2, dtype: string

In [11]:
base_casas

,entidad,municipio,localidad,nombre,id_temp_sus,aceptado,motivo_rechazo,clues_ancla,tiempo_min,dist_km,geometry
0,BAJA CALIFORNIA,ENSENADA,ENSENADA,CASA DE CUIDADO,BCN-SUS-0001,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCIMB000104,3.9,1.988,POINT (-116.56015 31.84882)
1,BAJA CALIFORNIA,ENSENADA,EJIDO FRANCISCO R. SERRANO (VALLE SAN MATÍAS),CASA DE SALUD KILIWAS,BCN-SUS-0002,Aceptada,Aceptada,BCIMB000314,43.9,22.735,POINT (-115.64778 31.26667)
2,BAJA CALIFORNIA,ENSENADA,LA HUERTA,CASA DE SALUD LA HUERTA,BCN-SUS-0003,Aceptada,Aceptada,BCIMB000191,35.8,17.404,POINT (-116.13491 31.93657)
3,BAJA CALIFORNIA,ENSENADA,SAN ANTONIO NECUA (CAÑADA DE LOS ENCINOS),CASA DE SALUD SAN ANTONIO NECUA,BCN-SUS-0004,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",BCIMB001270,11.8,8.667,POINT (-116.49811 32.1044)
4,BAJA CALIFORNIA,ENSENADA,ENSENADA,CASA DE SALUD SEXTO AYUNTAMIENTO,BCN-SUS-0005,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCIMB001516,2.2,0.834,POINT (-116.59193 31.78005)
...,...,...,...,...,...,...,...,...,...,...,...
3639,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ,VERACRUZ,EX CASETA DE POLICIA,VER-SUS-1208,Aceptada,Otra casa de salud ofrece una mejor ubicación,VZIMB005562,3.0,1.631,POINT (-96.1661 19.1989)
3640,VERACRUZ DE IGNACIO DE LA LLAVE,VERACRUZ,VERACRUZ,EX DIRECCIÓN DE DESARROLLO SOCIAL Y HUMANO,VER-SUS-1213,Aceptada,Otra casa de salud ofrece una mejor ubicación,VZIMB005545,5.1,3.351,POINT (-96.166 19.1842)
3641,YUCATAN,ESPITA,ESPITA,"KUNCHE, ESPITA, YUCATÁN",YUC-SUS-0057,No aceptada,No mejora ubicacion respecto a unidades existe...,QRIMB001471,102.2,100.632,POINT (-88.30703 21.01145)
3642,YUCATAN,MUXUPIP,MUXUPIP,CASA SALUD MUXUPIP,YUC-SUS-0121,No aceptada,No mejora ubicacion respecto a unidades existe...,CCIMB000020,98.1,114.708,POINT (-89.32971 21.04251)
3643,YUCATAN,SUMA,SUMA,CONSULTORIO,YUC-SUS-0157,No aceptada,No mejora ubicacion respecto a unidades existe...,CCIMB000020,109.7,139.923,POINT (-89.14565 21.08761)

In [12]:
base_casas.columns

Index(['entidad', 'municipio', 'localidad', 'nombre', 'id_temp_sus',
       'aceptado', 'motivo_rechazo', 'clues_ancla', 'tiempo_min', 'dist_km',
       'geometry'],
      dtype='object')

In [13]:
columnas_casas = ['entidad', 'municipio', 'localidad', 'nombre', 'aceptado', 'id_temp_sus', 'geometry']
print('Columna de aceptación:', 'aceptado' in base_casas.columns)
print('Filas:', len(base_casas))
print('Columnas requeridas faltantes:', sorted(set(columnas_casas) - set(base_casas.columns)))
print('Geometrías faltantes:', int(base_casas.geometry.isna().sum()))

Columna de aceptación: True
Filas: 3644
Columnas requeridas faltantes: []
Geometrías faltantes: 0

In [14]:
localidad = pd.read_excel(fr"C:\Users\jose.valdez\Downloads\mapa_imo\mapa_primer_nivel\base\tabla_de_asignacion_localidad.xlsx")

In [15]:
localidad

,cvegeo,clues_antes,duracion_antes,distancia_antes,clues_despues,duracion_despues,distancia_despues,poblacion_sin_derechohabiencia_2026,poblacion_total_2026,diferencia_tiempo,diferencia_distancia,optima_por_accesibilidad,nuevo_ambito,optima_acces_sin_vaciar,aceptado,motivo_rechazo,asignacion_final
0,0200100010026,BCIMB000063,2.3,938.0,BCN-SUS-0010,4.1,1794,26.0,69.0,-1.8,-856.0,BCIMB000063,Urbano,BCIMB000063,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCN-SUS-0010
1,0200100010030,BCIMB001451,9.3,5748.0,BCN-SUS-0005,10.0,6123,61.0,164.0,-0.7,-375.0,BCIMB001451,Urbano,BCIMB001451,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCN-SUS-0005
2,0200100010083,BCIMB001661,6.0,2807.0,BCN-SUS-0010,4.5,2582,589.0,1595.0,1.5,225.0,BCN-SUS-0010,Urbano,BCN-SUS-0010,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCN-SUS-0010
3,0200100010098,BCIMB001661,6.7,3214.0,BCN-SUS-0010,5.2,2989,878.0,2380.0,1.5,225.0,BCN-SUS-0010,Urbano,BCN-SUS-0010,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCN-SUS-0010
4,0200100010100,BCIMB000075,4.4,2540.0,BCN-SUS-0014,2.6,1151,1460.0,3957.0,1.8,1389.0,BCN-SUS-0014,Urbano,BCN-SUS-0014,Aceptada,Aceptada Ubicada en localidad altamente poblada,BCN-SUS-0014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182693,320101007,ZSIMB000241,11.6,7158.0,ZAC-SUS-0379,6.0,3193,0.0,0.0,5.6,3965.0,ZAC-SUS-0379,Rural,ZSIMB000241,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",ZSIMB000241
182694,320101009,ZSIMS000645,9.9,6581.0,ZAC-SUS-0379,7.1,4338,3.0,5.0,2.8,2243.0,ZAC-SUS-0379,Rural,ZAC-SUS-0379,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",ZSIMS000645
182695,320101195,ZSIMB000241,11.9,7266.0,ZAC-SUS-0379,6.2,3301,16.0,27.0,5.7,3965.0,ZAC-SUS-0379,Rural,ZSIMB000241,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",ZSIMB000241
182696,320101205,ZSIMB000241,11.8,7252.0,ZAC-SUS-0379,6.2,3287,10.0,17.0,5.6,3965.0,ZAC-SUS-0379,Rural,ZSIMB000241,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",ZSIMB000241
182697,320101260,ZSIMB000241,38.9,17712.0,ZAC-SUS-0379,30.3,12559,3.0,5.0,8.6,5153.0,ZAC-SUS-0379,Rural,ZSIMB000241,No aceptada,"R3. Deja una unidad existente por debajo de 1,...",ZSIMB000241

In [16]:
base = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\base_clues_imo_imb.gpkg")

In [17]:
base

,clues,institucion,entidad,municipio,localidad,nombre_de_la_unidad,geometry
0,BCIMS000513,IMS,BAJA CALIFORNIA,SAN QUINTIN,CAMALU,CAMALÚ,POINT (-116.06507 30.84503)
1,BCIMS000525,IMS,BAJA CALIFORNIA,SAN QUINTIN,LAZARO CARDENAS,LÁZARO CÁRDENAS (SAN QUINTIN),POINT (-115.92796 30.52928)
2,BCIMS000530,IMS,BAJA CALIFORNIA,ENSENADA,EJIDO PUNTA COLNETT (PUNTA COLONET),EJIDO MÉXICO (EJIDO PUNTA COLONET),POINT (-116.20818 31.07187)
3,BCIMS000542,IMS,BAJA CALIFORNIA,ENSENADA,SANTO TOMAS,SANTO TOMÁS (ENSENADA),POINT (-116.40101 31.54794)
4,BCIMS000554,IMS,BAJA CALIFORNIA,ENSENADA,EL PORVENIR (GUADALUPE),EL PORVENIR (GUADALUPE),POINT (-116.6241 32.07778)
...,...,...,...,...,...,...,...
11615,ZSIMB002464,IMB,ZACATECAS,VETAGRANDE,SAN JOSE DE LA ERA,CENTRO DE SALUD SAN JOSÉ DE LA ERA,POINT (-102.42279 22.85163)
11616,ZSIMB002505,IMB,ZACATECAS,RIO GRANDE,RIO GRANDE,CESSA RÍO GRANDE,POINT (-103.01225 23.82886)
11617,ZSIMB002522,IMB,ZACATECAS,FRESNILLO,FRESNILLO,CENTRO DE SALUD FRESNILLO 2,POINT (-102.86467 23.18379)
11618,ZSIMB002534,IMB,ZACATECAS,PINOS,PINOS,CESSA PINOS,POINT (-101.58206 22.27766)
11619,ZSIMB002650,IMB,ZACATECAS,JEREZ,JEREZ DE GARCIA SALINAS,CENTRO DE SALUD JEREZ,POINT (-102.98112 22.66193)

In [18]:
# sus = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\voronoi nuevo.gpkg")

In [19]:
consultorio = pd.read_excel(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\asignacion_definitiva_y_aprovechamiento.xlsx",sheet_name="Unidades",skiprows=2)

In [20]:
productividad =  pd.read_parquet(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\productividad_coplamar_imb.parquet")

In [21]:
unid = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\Unidades aceptadas_completo3.gpkg")
poligono = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\voronoi nuevo.gpkg")

In [22]:
# poligono = poligono.rename(columns={"CLUES":"CLUES_1"})

In [23]:
base

,clues,institucion,entidad,municipio,localidad,nombre_de_la_unidad,geometry
0,BCIMS000513,IMS,BAJA CALIFORNIA,SAN QUINTIN,CAMALU,CAMALÚ,POINT (-116.06507 30.84503)
1,BCIMS000525,IMS,BAJA CALIFORNIA,SAN QUINTIN,LAZARO CARDENAS,LÁZARO CÁRDENAS (SAN QUINTIN),POINT (-115.92796 30.52928)
2,BCIMS000530,IMS,BAJA CALIFORNIA,ENSENADA,EJIDO PUNTA COLNETT (PUNTA COLONET),EJIDO MÉXICO (EJIDO PUNTA COLONET),POINT (-116.20818 31.07187)
3,BCIMS000542,IMS,BAJA CALIFORNIA,ENSENADA,SANTO TOMAS,SANTO TOMÁS (ENSENADA),POINT (-116.40101 31.54794)
4,BCIMS000554,IMS,BAJA CALIFORNIA,ENSENADA,EL PORVENIR (GUADALUPE),EL PORVENIR (GUADALUPE),POINT (-116.6241 32.07778)
...,...,...,...,...,...,...,...
11615,ZSIMB002464,IMB,ZACATECAS,VETAGRANDE,SAN JOSE DE LA ERA,CENTRO DE SALUD SAN JOSÉ DE LA ERA,POINT (-102.42279 22.85163)
11616,ZSIMB002505,IMB,ZACATECAS,RIO GRANDE,RIO GRANDE,CESSA RÍO GRANDE,POINT (-103.01225 23.82886)
11617,ZSIMB002522,IMB,ZACATECAS,FRESNILLO,FRESNILLO,CENTRO DE SALUD FRESNILLO 2,POINT (-102.86467 23.18379)
11618,ZSIMB002534,IMB,ZACATECAS,PINOS,PINOS,CESSA PINOS,POINT (-101.58206 22.27766)
11619,ZSIMB002650,IMB,ZACATECAS,JEREZ,JEREZ DE GARCIA SALINAS,CENTRO DE SALUD JEREZ,POINT (-102.98112 22.66193)

In [24]:
poligono.columns = poligono.columns.str.lower().str.replace(' ', '_')

In [25]:
unid.columns = unid.columns.str.lower().str.replace(' ', '_')

In [26]:
consultorio.columns = consultorio.columns.str.lower().str.replace(' ', '_')
consultorio['clues'] = consultorio['clues'].astype(str).str.strip()
consultorio['_escenario_normalizado'] = (
    consultorio['escenario'].astype('string').str.strip().str.casefold()
)
consultorio['_prioridad'] = (
    consultorio['_escenario_normalizado']
    .map({
        'Después'.casefold(): 0,
        'Nuevas (casas de salud)'.casefold(): 1,
    })
    .fillna(2)
)
filas_consultorio_originales = len(consultorio)
consultorio = (
    consultorio
    .sort_values('_prioridad', kind='stable')
    .drop_duplicates(subset='clues', keep='first')
    .drop(columns=['_escenario_normalizado', '_prioridad'])
    .reset_index(drop=True)
)

print(f"Consultorios antes de priorizar: {filas_consultorio_originales:,}")
print(f"CLUES únicas después de priorizar: {len(consultorio):,}")

Consultorios antes de priorizar: 30,344
CLUES únicas después de priorizar: 15,439

In [27]:
poligono = poligono.rename(columns={'clues_final': 'clues'})

In [28]:
poligono.columns

Index(['fid', 'cvegeo', 'pobtot', 'pobfem', 'pobmas', 'p_0a2', 'pob0_14',
       'p_60ymas', 'p_60ymas_f', 'p_60ymas_m', 'p_15a49_f', 'psinder',
       'pder_ss', 'pder_imss', 'pder_segp', 'pder_imssb', 'pder_iste',
       'pder_istee', 'pafil_pdom', 'sin_der', 'entidad', 'clues_sin',
       'clues_con', 'se_reasigna', 'duracion_sin', 'duracion_con',
       'diferencia_duracion', 'distancia_sin', 'distancia_con',
       'diferencia_distancia', 'poblacion_total_2026',
       'poblacion_sin_derechohabiencia_2026', 'cambio_categorico', 'clues',
       'geometry'],
      dtype='object')

In [29]:
diagnostico_geometrico = {
    "poligono_crs": str(poligono.crs),
    "poligono_tipos": poligono.geom_type.value_counts().to_dict(),
    "poligono_registros": len(poligono),
    "poligono_clues_unicas": poligono["clues"].nunique(dropna=True),
    "poligono_geometrias_validas": int(poligono.geometry.is_valid.sum()),
    "unid_crs": str(unid.crs),
    "unid_tipos": unid.geom_type.value_counts().to_dict(),
    "unid_registros": len(unid),
    "unid_clues_unicas": unid["clues"].nunique(dropna=True),
}
diagnostico_geometrico

{'poligono_crs': 'EPSG:4326',
 'poligono_tipos': {'MultiPolygon': 15370},
 'poligono_registros': 15370,
 'poligono_clues_unicas': 15369,
 'poligono_geometrias_validas': 15370,
 'unid_crs': 'EPSG:4326',
 'unid_tipos': {'Point': 8600},
 'unid_registros': 8600,
 'unid_clues_unicas': 5041}

In [30]:
poligono_metrico = poligono.to_crs("EPSG:6372")
complejidad_original = int(poligono_metrico.geometry.get_coordinates().shape[0])
pruebas_simplificacion = {}

for tolerancia_m in (100, 250, 500):
    geometria_simplificada = poligono_metrico.geometry.simplify(
        tolerancia_m,
        preserve_topology=True,
    )
    pruebas_simplificacion[tolerancia_m] = {
        "coordenadas": int(geometria_simplificada.get_coordinates().shape[0]),
        "reduccion_pct": round(
            (1 - geometria_simplificada.get_coordinates().shape[0] / complejidad_original) * 100,
            1,
        ),
    }

{"coordenadas_originales": complejidad_original, "pruebas": pruebas_simplificacion}

{'coordenadas_originales': 936113,
 'pruebas': {100: {'coordenadas': 328935, 'reduccion_pct': 64.9},
  250: {'coordenadas': 246135, 'reduccion_pct': 73.7},
  500: {'coordenadas': 183085, 'reduccion_pct': 80.4}}}

In [31]:
import json
import zlib
from pathlib import Path

salida_voronoi = Path.cwd() / "public" / "voronoi"
salida_voronoi.mkdir(parents=True, exist_ok=True)

for archivo_anterior in salida_voronoi.glob("*.geojson"):
    archivo_anterior.unlink()

voronoi_web = poligono.loc[
    poligono["clues"].notna(),
    ["clues", "geometry"],
].copy()
voronoi_web["clues"] = voronoi_web["clues"].astype(str).str.strip()
voronoi_web["fragmento_id"] = voronoi_web["clues"].map(
    lambda clues: zlib.crc32(clues.encode("utf-8")) % 32
)
voronoi_web = voronoi_web.to_crs("EPSG:6372")
voronoi_web["geometry"] = voronoi_web.geometry.simplify(100, preserve_topology=True)
voronoi_web = voronoi_web.to_crs("EPSG:4326")

indice_voronoi = {}
for fragmento_id, fragmento in voronoi_web.groupby("fragmento_id", sort=True):
    nombre_archivo = f"fragmento-{fragmento_id:02d}.geojson"
    fragmento_salida = fragmento[["clues", "geometry"]].copy()
    (salida_voronoi / nombre_archivo).write_text(
        fragmento_salida.to_json(drop_id=True, separators=(",", ":")),
        encoding="utf-8",
    )
    indice_voronoi.update(dict.fromkeys(fragmento_salida["clues"], nombre_archivo))

(salida_voronoi / "index.json").write_text(
    json.dumps(indice_voronoi, ensure_ascii=False, separators=(",", ":")),
    encoding="utf-8",
)

tamanos_fragmentos = [archivo.stat().st_size for archivo in salida_voronoi.glob("*.geojson")]
tamano_mb = sum(archivo.stat().st_size for archivo in salida_voronoi.iterdir()) / 1024**2
print(f"Voronoi exportado: {len(voronoi_web):,} polígonos en {len(tamanos_fragmentos)} fragmentos")
print(f"Índice: {len(indice_voronoi):,} CLUES")
print(f"Tamaño total: {tamano_mb:.1f} MB")
print(f"Fragmento mayor: {max(tamanos_fragmentos) / 1024**2:.1f} MB")

Voronoi exportado: 15,369 polígonos en 32 fragmentos
Índice: 15,369 CLUES
Tamaño total: 14.4 MB
Fragmento mayor: 0.5 MB

In [32]:
for nombre, gdf in {"poligono": poligono, "unid": unid}.items():
    print(nombre)
    print("CRS:", gdf.crs)
    print(gdf.geom_type.value_counts())
    print("Registros:", len(gdf))

poligono
CRS: EPSG:4326
MultiPolygon    15370
Name: count, dtype: int64
Registros: 15370
unid
CRS: EPSG:4326
Point    8600
Name: count, dtype: int64
Registros: 8600

In [33]:
unid.columns

Index(['uid', 'id_temp_sus', 'id_temp_sheets_edos', 'operador',
       'institucion_que_propone_espacio', 'entidad', 'municipio', 'nombre',
       'clues', 'estrato', 'mod_id', 'modalidad', 'lat', 'lon',
       'origen_estrato', 'cluster_rural_id', 'cluster_rural_tamano_unidades',
       'regla_cluster', 'motivo_decision', 'estatus_final', 'num_consultorios',
       'fid', 'cvegeo', 'pobtot', 'pobfem', 'pobmas', 'p_0a2', 'pob0_14',
       'p_60ymas', 'p_60ymas_f', 'p_60ymas_m', 'p_15a49_f', 'psinder',
       'pder_ss', 'pder_imss', 'pder_segp', 'pder_imssb', 'pder_iste',
       'pder_istee', 'pafil_pdom', 'sin_der', 'nom_mun', 'dist_km', 'dur_min',
       'clues_2', 'institucion', 'nombre_unidad',
       'población_con_derechohabiencia_2026',
       'población_sin_derechohabiencia_2026', 'población_total_2026',
       'geometry'],
      dtype='object')

In [34]:
productividad

,clues,nombre_de_la_unidad,entidad,cve_ent,municipio,cve_mun,localidad,cve_loc,cvegeo,poblacion_con_derechohabiencia_2026,consulta_general
0,YNSSA014046,CENTRO DE SALUD DE MOTUL,YUCATAN,31,MOTUL,052,MOTUL DE CARRILLO PUERTO,0001,310520001,0.0,NaN
1,HGIMB000035,SAN BARTOLO,HIDALGO,13,ACATLAN,001,SAN BARTOLO (EL LLANO),0020,130010020,0.0,2251.0
2,SPIMB002516,CENTRO DE SALUD HUEHUETLAN,SAN LUIS POTOSI,24,HUEHUETLAN,018,HUEHUETLAN,0001,240180001,1.0,5824.0
3,YNSSA000705,CENTRO DE SALUD XOHUAYAN,YUCATAN,31,OXKUTZCAB,056,XOHUAYAN,0013,310560013,10.0,NaN
4,CMIMB000260,CENTRO DE SALUD CAMPO CUATRO,COLIMA,06,COMALA,003,CAMPO CUATRO,0008,060030008,11.0,807.0
...,...,...,...,...,...,...,...,...,...,...,...
11595,SRIMB002401,CENTRO DE SALUD URBANO NOGALES,SONORA,26,NOGALES,043,HEROICA NOGALES,0001,260430001,179373.0,17753.0
11596,YNSSA000466,CENTRO DE SALUD KANASÍN,YUCATAN,31,KANASIN,041,KANASIN,0001,310410001,190863.0,NaN
11597,QRIMB001430,CENTRO DE SALUD URBANO 01 PLAYA DEL CARMEN,QUINTANA ROO,23,SOLIDARIDAD,008,PLAYA DEL CARMEN,0001,230080001,182283.0,1900.0
11598,SLIMB003012,CENTRO DE SALUD MOCHIS II,SINALOA,25,AHOME,001,LOS MOCHIS,0001,250010001,193982.0,59650.0
11599,YNSSA000611,CENTRO SALUD MÉRIDA,YUCATAN,31,MERIDA,050,MERIDA,0001,310500001,267932.0,NaN

In [35]:
productividad

,clues,nombre_de_la_unidad,entidad,cve_ent,municipio,cve_mun,localidad,cve_loc,cvegeo,poblacion_con_derechohabiencia_2026,consulta_general
0,YNSSA014046,CENTRO DE SALUD DE MOTUL,YUCATAN,31,MOTUL,052,MOTUL DE CARRILLO PUERTO,0001,310520001,0.0,NaN
1,HGIMB000035,SAN BARTOLO,HIDALGO,13,ACATLAN,001,SAN BARTOLO (EL LLANO),0020,130010020,0.0,2251.0
2,SPIMB002516,CENTRO DE SALUD HUEHUETLAN,SAN LUIS POTOSI,24,HUEHUETLAN,018,HUEHUETLAN,0001,240180001,1.0,5824.0
3,YNSSA000705,CENTRO DE SALUD XOHUAYAN,YUCATAN,31,OXKUTZCAB,056,XOHUAYAN,0013,310560013,10.0,NaN
4,CMIMB000260,CENTRO DE SALUD CAMPO CUATRO,COLIMA,06,COMALA,003,CAMPO CUATRO,0008,060030008,11.0,807.0
...,...,...,...,...,...,...,...,...,...,...,...
11595,SRIMB002401,CENTRO DE SALUD URBANO NOGALES,SONORA,26,NOGALES,043,HEROICA NOGALES,0001,260430001,179373.0,17753.0
11596,YNSSA000466,CENTRO DE SALUD KANASÍN,YUCATAN,31,KANASIN,041,KANASIN,0001,310410001,190863.0,NaN
11597,QRIMB001430,CENTRO DE SALUD URBANO 01 PLAYA DEL CARMEN,QUINTANA ROO,23,SOLIDARIDAD,008,PLAYA DEL CARMEN,0001,230080001,182283.0,1900.0
11598,SLIMB003012,CENTRO DE SALUD MOCHIS II,SINALOA,25,AHOME,001,LOS MOCHIS,0001,250010001,193982.0,59650.0
11599,YNSSA000611,CENTRO SALUD MÉRIDA,YUCATAN,31,MERIDA,050,MERIDA,0001,310500001,267932.0,NaN

In [36]:
consultorio.columns

Index(['escenario', 'clues', 'tipo_de_unidad', 'localidades',
       'población_total_2026', 'población_sin_derechohabiencia_2026',
       'consultorios_habilitados', 'consultorios_inhabilitados',
       'total_consultorios', 'consultorios_usados',
       'población_por_consultorio', 'razón_de_aprovechamiento', 'categoría',
       'supuesto_1_consultorio'],
      dtype='object')

In [37]:
len(consultorio)

15439

In [38]:
len(base)

11620

In [39]:
base.columns

Index(['clues', 'institucion', 'entidad', 'municipio', 'localidad',
       'nombre_de_la_unidad', 'geometry'],
      dtype='object')

In [40]:
consultorio

,escenario,clues,tipo_de_unidad,localidades,población_total_2026,población_sin_derechohabiencia_2026,consultorios_habilitados,consultorios_inhabilitados,total_consultorios,consultorios_usados,población_por_consultorio,razón_de_aprovechamiento,categoría,supuesto_1_consultorio
0,Después,BCIMB000051,IMSS Bienestar,5,5730,2116,5.0,1.0,6.0,6,955.000000,0.318333,<0.50,No
1,Después,BCIMB000063,IMSS Bienestar,8,10546,3893,3.0,0.0,3.0,3,3515.333333,1.171778,0.80–1.20,No
2,Después,BCIMB000075,IMSS Bienestar,23,22289,8229,3.0,0.0,3.0,3,7429.666667,2.476556,>1.50,No
3,Después,BCIMB000080,IMSS Bienestar,17,26387,9739,7.0,0.0,7.0,7,3769.571429,1.256524,>1.20–1.50,No
4,Después,BCIMB000092,IMSS Bienestar,13,10683,3943,3.0,0.0,3.0,3,3561.000000,1.187000,0.80–1.20,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15434,Antes,YNSSA001154,IMSS Bienestar,46,30711,21144,2.0,0.0,2.0,2,15355.500000,5.118500,>1.50,No
15435,Antes,YNSSA001562,IMSS Bienestar,4,2074,1426,1.0,0.0,1.0,1,2074.000000,0.691333,0.50–<0.80,No
15436,Antes,YNSSA002535,IMSS Bienestar,5,1904,1282,3.0,0.0,3.0,3,634.666667,0.211556,<0.50,No
15437,Antes,YNSSA014080,IMSS Bienestar,6,3758,3415,1.0,0.0,1.0,1,3758.000000,1.252667,>1.20–1.50,No
15438,Antes,YNSSA014215,IMSS Bienestar,17,2208,1111,2.0,0.0,2.0,2,1104.000000,0.368000,<0.50,No

In [41]:
base

,clues,institucion,entidad,municipio,localidad,nombre_de_la_unidad,geometry
0,BCIMS000513,IMS,BAJA CALIFORNIA,SAN QUINTIN,CAMALU,CAMALÚ,POINT (-116.06507 30.84503)
1,BCIMS000525,IMS,BAJA CALIFORNIA,SAN QUINTIN,LAZARO CARDENAS,LÁZARO CÁRDENAS (SAN QUINTIN),POINT (-115.92796 30.52928)
2,BCIMS000530,IMS,BAJA CALIFORNIA,ENSENADA,EJIDO PUNTA COLNETT (PUNTA COLONET),EJIDO MÉXICO (EJIDO PUNTA COLONET),POINT (-116.20818 31.07187)
3,BCIMS000542,IMS,BAJA CALIFORNIA,ENSENADA,SANTO TOMAS,SANTO TOMÁS (ENSENADA),POINT (-116.40101 31.54794)
4,BCIMS000554,IMS,BAJA CALIFORNIA,ENSENADA,EL PORVENIR (GUADALUPE),EL PORVENIR (GUADALUPE),POINT (-116.6241 32.07778)
...,...,...,...,...,...,...,...
11615,ZSIMB002464,IMB,ZACATECAS,VETAGRANDE,SAN JOSE DE LA ERA,CENTRO DE SALUD SAN JOSÉ DE LA ERA,POINT (-102.42279 22.85163)
11616,ZSIMB002505,IMB,ZACATECAS,RIO GRANDE,RIO GRANDE,CESSA RÍO GRANDE,POINT (-103.01225 23.82886)
11617,ZSIMB002522,IMB,ZACATECAS,FRESNILLO,FRESNILLO,CENTRO DE SALUD FRESNILLO 2,POINT (-102.86467 23.18379)
11618,ZSIMB002534,IMB,ZACATECAS,PINOS,PINOS,CESSA PINOS,POINT (-101.58206 22.27766)
11619,ZSIMB002650,IMB,ZACATECAS,JEREZ,JEREZ DE GARCIA SALINAS,CENTRO DE SALUD JEREZ,POINT (-102.98112 22.66193)

In [42]:
base['clues'] = base['clues'].astype(str).str.strip()
base = (
    base
    .drop(columns=['total_consultorios', 'población_por_consultorio'], errors='ignore')
    .drop_duplicates(subset='clues', keep='first')
    .merge(
        consultorio[['clues', 'total_consultorios', 'población_por_consultorio']],
        on='clues',
        how='left',
        validate='one_to_one',
    )
)

print(f"Base después del merge de consultorios: {len(base):,} filas")

Base después del merge de consultorios: 11,620 filas

In [43]:
len(base)

11620

In [44]:
base = base.merge(
    productividad[['clues','consulta_general']],
    on='clues',
    how='left'
)

In [45]:
len(base)

11620

In [46]:
base.columns

Index(['clues', 'institucion', 'entidad', 'municipio', 'localidad',
       'nombre_de_la_unidad', 'geometry', 'total_consultorios',
       'población_por_consultorio', 'consulta_general'],
      dtype='object')

In [47]:
# base = base[base["nivel_atencion"]=="PRIMER NIVEL"]

In [48]:
# tipologias = [
#     'CENTROS DE SALUD CON SERVICIOS AMPLIADOS',
#     'UNIDAD MÓVIL',
#     'URBANO DE 01 NÚCLEOS BÁSICOS',
#     'URBANO DE 05 NÚCLEOS BÁSICOS',
#     'RURAL DE 01 NÚCLEO BÁSICO',
#     'URBANO DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 11 NÚCLEOS BÁSICOS',
#     'URBANO DE 12 NÚCLEOS BÁSICOS Y MÁS',
#     'RURAL DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 06 NÚCLEOS BÁSICOS',
#     'URBANO DE 03 NÚCLEOS BÁSICOS',
#     'URBANO DE 07 NÚCLEOS BÁSICOS',
#     'URBANO DE 08 NÚCLEOS BÁSICOS',
#     'URBANO DE 04 NÚCLEOS BÁSICOS'
# ]

# base = base[base['NOMBRE DE TIPOLOGIA'].isin(tipologias)]

In [49]:
conteo_imo = base["institucion"].unique()
conteo_imo

array(['IMS', 'IMB'], dtype=object)

In [50]:
base.columns

Index(['clues', 'institucion', 'entidad', 'municipio', 'localidad',
       'nombre_de_la_unidad', 'geometry', 'total_consultorios',
       'población_por_consultorio', 'consulta_general'],
      dtype='object')

In [51]:
len(base)

11620

In [52]:
from pathlib import Path

columnas_unidades = [
    'clues', 'nombre_de_la_unidad', 'institucion', 'entidad', 'municipio', 'localidad', 'geometry'
]
columnas_casas = ['entidad', 'municipio', 'localidad', 'nombre', 'aceptado', 'id_temp_sus', 'geometry']

consultorio_mapa = consultorio.loc[:, [
    'clues', 'total_consultorios', 'población_por_consultorio'
]].copy()

productividad_mapa = productividad.loc[:, ['clues', 'consulta_general']].copy()
productividad_mapa['clues'] = productividad_mapa['clues'].astype(str).str.strip()

base_unidades = base.loc[
    base['institucion'].isin(['IMS', 'IMB']),
    columnas_unidades,
].copy()
base_unidades = base_unidades.rename(columns={'nombre_de_la_unidad': 'nombre_unidad'})
base_unidades['institucion'] = base_unidades['institucion'].replace({'IMS': 'IMO'})
base_unidades['clues'] = base_unidades['clues'].astype(str).str.strip()
base_unidades = base_unidades.drop_duplicates(subset='clues', keep='first')
base_unidades = base_unidades.merge(consultorio_mapa, on='clues', how='left', validate='one_to_one')
base_unidades = base_unidades.merge(productividad_mapa, on='clues', how='left', validate='many_to_one')
base_unidades['accion'] = None
base_unidades['id_temp_sus'] = None

casas_mapa = pd.concat([
    base_casas_aceptadas.loc[:, columnas_casas],
    base_casas_no_aceptadas.loc[:, columnas_casas],
], ignore_index=True).copy()
casas_mapa['accion'] = casas_mapa['aceptado']
casas_mapa['id_temp_sus'] = casas_mapa['id_temp_sus'].astype('string').str.strip()
casas_mapa = casas_mapa[
    casas_mapa['id_temp_sus'].notna()
    & casas_mapa['id_temp_sus'].ne('')
    & casas_mapa.geometry.notna()
].reset_index(drop=True)
casas_mapa['clues'] = casas_mapa['id_temp_sus']
casas_mapa = casas_mapa.rename(columns={'nombre': 'nombre_unidad'})
casas_mapa['institucion'] = 'CSA'
casas_mapa['total_consultorios'] = None
casas_mapa['población_por_consultorio'] = None
casas_mapa['consulta_general'] = None
casas_mapa = gpd.GeoDataFrame(
    casas_mapa,
    geometry='geometry',
    crs=base_casas.crs,
).to_crs(base_unidades.crs)

columnas_salida = [
    'clues', 'id_temp_sus', 'nombre_unidad', 'institucion', 'entidad', 'municipio', 'localidad',
    'accion', 'total_consultorios', 'población_por_consultorio', 'consulta_general', 'geometry'
]
base_mapa = gpd.GeoDataFrame(
    pd.concat([
        base_unidades.loc[:, columnas_salida],
        casas_mapa.loc[:, columnas_salida],
    ], ignore_index=True),
    geometry='geometry',
    crs=base_unidades.crs,
)

salida_mapa = Path.cwd() / 'public' / 'mapa_base.geojson'
base_mapa.to_file(salida_mapa, driver='GeoJSON')

print(base_mapa['institucion'].value_counts().to_dict())
print(f'GeoJSON generado: {salida_mapa} ({len(base_mapa):,} unidades)')
print(f"Casas de salud exportadas: {(base_mapa['institucion'] == 'CSA').sum():,}")
print(f"Unidades con consultorios: {base_mapa['total_consultorios'].notna().sum():,}")
print(f"Unidades con consulta general: {base_mapa['consulta_general'].notna().sum():,}")

C:\Users\jose.valdez\AppData\Local\Temp\ipykernel_4340\1969841993.py:56: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat([

{'IMB': 8379, 'CSA': 3644, 'IMO': 3241}
GeoJSON generado: C:\Users\jose.valdez\Downloads\mapa_imo\mapa_primer_nivel\public\mapa_base.geojson (15,264 unidades)
Casas de salud exportadas: 3,644
Unidades con consultorios: 8,368
Unidades con consulta general: 11,327

In [53]:
escenario_normalizado = consultorio['escenario'].astype('string').str.strip().str.casefold()
consultorio_auditoria = consultorio.assign(
    _escenario_normalizado=escenario_normalizado,
    _prioridad=escenario_normalizado.map({
        'Después'.casefold(): 0,
        'Nuevas (casas de salud)'.casefold(): 1,
    }).fillna(2),
)
seleccion_auditoria = (
    consultorio_auditoria
    .sort_values('_prioridad', kind='stable')
    .drop_duplicates('clues', keep='first')
    .set_index('clues')
)
escenarios_por_clues = consultorio_auditoria.groupby('clues')['_escenario_normalizado'].agg(set)
esperados = escenarios_por_clues.map(
    lambda escenarios: (
        'Después'.casefold() if 'Después'.casefold() in escenarios
        else 'Nuevas (casas de salud)'.casefold()
        if 'Nuevas (casas de salud)'.casefold() in escenarios
        else None
    )
)
comparables = esperados.notna()
incumplimientos = seleccion_auditoria.loc[comparables, '_escenario_normalizado'] != esperados[comparables]

print(f"CLUES de consultorio revisadas: {len(seleccion_auditoria):,}")
print(f"Seleccionadas como Después: {(seleccion_auditoria['_escenario_normalizado'] == 'Después'.casefold()).sum():,}")
print(f"Seleccionadas como Nuevas (casas de salud): {(seleccion_auditoria['_escenario_normalizado'] == 'Nuevas (casas de salud)'.casefold()).sum():,}")
print(f"Incumplimientos de prioridad: {incumplimientos.sum():,}")
print(f"CLUES únicas exportadas: {base_mapa['clues'].nunique():,} de {len(base_mapa):,} filas")

CLUES de consultorio revisadas: 15,439
Seleccionadas como Después: 15,369
Seleccionadas como Nuevas (casas de salud): 0
Incumplimientos de prioridad: 0
CLUES únicas exportadas: 15,264 de 15,264 filas