In [1]:
import geopandas as gpd
import  os 
import pandas as pd 
usuario = os.getlogin()

In [2]:

# yucatan = gpd.read_file(fr"C:\Users\{usuario}\Downloads\Anexo_1_yuc_validado.gpkg")

In [2]:
base = gpd.read_file(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\UPN_IMO_IMB_CASASSALUD_sin_CESSA.gpkg")

In [3]:
consultorio = pd.read_excel(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\asignacion_definitiva_y_aprovechamiento.xlsx",sheet_name="Unidades",skiprows=2)

In [4]:
productividad =  pd.read_parquet(fr"C:\Users\{usuario}\Downloads\mapa_imo\mapa_primer_nivel\base\productividad_coplamar_imb.parquet")

In [5]:
consultorio.columns = consultorio.columns.str.lower().str.replace(' ', '_')

In [7]:
productividad

,clues,nombre_de_la_unidad,entidad,cve_ent,municipio,cve_mun,localidad,cve_loc,cvegeo,poblacion_con_derechohabiencia_2026,consulta_general
0,YNSSA014046,CENTRO DE SALUD DE MOTUL,YUCATAN,31,MOTUL,052,MOTUL DE CARRILLO PUERTO,0001,310520001,0.0,NaN
1,HGIMB000035,SAN BARTOLO,HIDALGO,13,ACATLAN,001,SAN BARTOLO (EL LLANO),0020,130010020,0.0,2251.0
2,SPIMB002516,CENTRO DE SALUD HUEHUETLAN,SAN LUIS POTOSI,24,HUEHUETLAN,018,HUEHUETLAN,0001,240180001,1.0,5824.0
3,YNSSA000705,CENTRO DE SALUD XOHUAYAN,YUCATAN,31,OXKUTZCAB,056,XOHUAYAN,0013,310560013,10.0,NaN
4,CMIMB000260,CENTRO DE SALUD CAMPO CUATRO,COLIMA,06,COMALA,003,CAMPO CUATRO,0008,060030008,11.0,807.0
...,...,...,...,...,...,...,...,...,...,...,...
11595,SRIMB002401,CENTRO DE SALUD URBANO NOGALES,SONORA,26,NOGALES,043,HEROICA NOGALES,0001,260430001,179373.0,17753.0
11596,YNSSA000466,CENTRO DE SALUD KANASÍN,YUCATAN,31,KANASIN,041,KANASIN,0001,310410001,190863.0,NaN
11597,QRIMB001430,CENTRO DE SALUD URBANO 01 PLAYA DEL CARMEN,QUINTANA ROO,23,SOLIDARIDAD,008,PLAYA DEL CARMEN,0001,230080001,182283.0,1900.0
11598,SLIMB003012,CENTRO DE SALUD MOCHIS II,SINALOA,25,AHOME,001,LOS MOCHIS,0001,250010001,193982.0,59650.0
11599,YNSSA000611,CENTRO SALUD MÉRIDA,YUCATAN,31,MERIDA,050,MERIDA,0001,310500001,267932.0,NaN

In [23]:
productividad

,clues,nombre_de_la_unidad,entidad,cve_ent,municipio,cve_mun,localidad,cve_loc,cvegeo,poblacion_con_derechohabiencia_2026,consulta_general
0,YNSSA014046,CENTRO DE SALUD DE MOTUL,YUCATAN,31,MOTUL,052,MOTUL DE CARRILLO PUERTO,0001,310520001,0.0,NaN
1,HGIMB000035,SAN BARTOLO,HIDALGO,13,ACATLAN,001,SAN BARTOLO (EL LLANO),0020,130010020,0.0,2251.0
2,SPIMB002516,CENTRO DE SALUD HUEHUETLAN,SAN LUIS POTOSI,24,HUEHUETLAN,018,HUEHUETLAN,0001,240180001,1.0,5824.0
3,YNSSA000705,CENTRO DE SALUD XOHUAYAN,YUCATAN,31,OXKUTZCAB,056,XOHUAYAN,0013,310560013,10.0,NaN
4,CMIMB000260,CENTRO DE SALUD CAMPO CUATRO,COLIMA,06,COMALA,003,CAMPO CUATRO,0008,060030008,11.0,807.0
...,...,...,...,...,...,...,...,...,...,...,...
11595,SRIMB002401,CENTRO DE SALUD URBANO NOGALES,SONORA,26,NOGALES,043,HEROICA NOGALES,0001,260430001,179373.0,17753.0
11596,YNSSA000466,CENTRO DE SALUD KANASÍN,YUCATAN,31,KANASIN,041,KANASIN,0001,310410001,190863.0,NaN
11597,QRIMB001430,CENTRO DE SALUD URBANO 01 PLAYA DEL CARMEN,QUINTANA ROO,23,SOLIDARIDAD,008,PLAYA DEL CARMEN,0001,230080001,182283.0,1900.0
11598,SLIMB003012,CENTRO DE SALUD MOCHIS II,SINALOA,25,AHOME,001,LOS MOCHIS,0001,250010001,193982.0,59650.0
11599,YNSSA000611,CENTRO SALUD MÉRIDA,YUCATAN,31,MERIDA,050,MERIDA,0001,310500001,267932.0,NaN

In [8]:
consultorio.columns

Index(['escenario', 'clues', 'tipo_de_unidad', 'localidades',
       'población_total_2026', 'población_sin_derechohabiencia_2026',
       'consultorios_habilitados', 'consultorios_inhabilitados',
       'total_consultorios', 'consultorios_usados',
       'población_por_consultorio', 'razón_de_aprovechamiento', 'categoría',
       'supuesto_1_consultorio'],
      dtype='object')

In [25]:
len(consultorio)

30344

In [10]:
len(base)

15323

In [10]:
base.columns

Index(['clues', 'nombre_unidad', 'institucion', 'entidad', 'municipio',
       'geometry'],
      dtype='object')

In [11]:
base = base.merge(
    consultorio[['clues', 'total_consultorios', 'población_por_consultorio']],
    on='clues',
    how='left'
)

In [13]:
base = base.merge(
    productividad[['clues','consulta_general']],
    on='clues',
    how='left'
)

In [14]:
len(base)

29917

In [14]:
base.columns

Index(['clues', 'nombre_unidad', 'institucion', 'entidad', 'municipio',
       'geometry', 'total_consultorios', 'población_por_consultorio',
       'consulta_general'],
      dtype='object')

In [15]:
# base = base[base["nivel_atencion"]=="PRIMER NIVEL"]

In [16]:
# tipologias = [
#     'CENTROS DE SALUD CON SERVICIOS AMPLIADOS',
#     'UNIDAD MÓVIL',
#     'URBANO DE 01 NÚCLEOS BÁSICOS',
#     'URBANO DE 05 NÚCLEOS BÁSICOS',
#     'RURAL DE 01 NÚCLEO BÁSICO',
#     'URBANO DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 11 NÚCLEOS BÁSICOS',
#     'URBANO DE 12 NÚCLEOS BÁSICOS Y MÁS',
#     'RURAL DE 02 NÚCLEOS BÁSICOS',
#     'URBANO DE 06 NÚCLEOS BÁSICOS',
#     'URBANO DE 03 NÚCLEOS BÁSICOS',
#     'URBANO DE 07 NÚCLEOS BÁSICOS',
#     'URBANO DE 08 NÚCLEOS BÁSICOS',
#     'URBANO DE 04 NÚCLEOS BÁSICOS'
# ]

# base = base[base['NOMBRE DE TIPOLOGIA'].isin(tipologias)]

In [17]:
conteo_imo = base["institucion"].unique()
conteo_imo

array(['IMB', 'IMS', 'CSA'], dtype=object)

In [10]:
base.columns

Index(['clues', 'nombre_unidad', 'institucion', 'entidad', 'municipio',
       'geometry'],
      dtype='object')

In [31]:
len(base)

15323

In [34]:
from pathlib import Path

columnas_mapa = [
    'clues', 'nombre_unidad', 'institucion', 'entidad', 'municipio', 'geometry'
]

consultorio_mapa = consultorio.loc[:, [
    'clues', 'escenario', 'total_consultorios', 'población_por_consultorio'
]].copy()
consultorio_mapa['clues'] = consultorio_mapa['clues'].astype(str).str.strip()
consultorio_mapa['_prioridad'] = (
    consultorio_mapa['escenario'].astype('string').str.strip().str.casefold()
    != 'Después'.casefold()
)
consultorio_mapa = (
    consultorio_mapa
    .sort_values('_prioridad', kind='stable')
    .drop_duplicates(subset='clues', keep='first')
    .drop(columns=['escenario', '_prioridad'])
)

productividad_mapa = productividad.loc[:, ['clues', 'consulta_general']].copy()
productividad_mapa['clues'] = productividad_mapa['clues'].astype(str).str.strip()

base_mapa = base.loc[
    base["institucion"].isin(["IMS", "IMB", "CSA"]),
    columnas_mapa,
].copy()

base_mapa["institucion"] = base_mapa["institucion"].replace({"IMS": "IMO"})
base_mapa['clues'] = base_mapa['clues'].astype(str).str.strip()
base_mapa = base_mapa.merge(consultorio_mapa, on='clues', how='left', validate='many_to_one')
base_mapa = base_mapa.merge(productividad_mapa, on='clues', how='left', validate='many_to_one')

salida_mapa = Path.cwd() / "public" / "mapa_base.geojson"
base_mapa.to_file(salida_mapa, driver="GeoJSON")

print(base_mapa["institucion"].value_counts().to_dict())
print(f"GeoJSON generado: {salida_mapa} ({len(base_mapa):,} CLUES)")
print(f"CLUES con consultorios: {base_mapa['total_consultorios'].notna().sum():,}")
print(f"CLUES con consulta general: {base_mapa['consulta_general'].notna().sum():,}")

{'IMB': 8077, 'CSA': 4012, 'IMO': 3234}
GeoJSON generado: c:\Users\jose.valdez\Downloads\mapa_imo\mapa_primer_nivel\public\mapa_base.geojson (15,323 CLUES)
CLUES con consultorios: 8,052
CLUES con consulta general: 11,010